export interface Category {
  cover: string;
  deliveryPrice: string;
  discountType: string;
  discountValue: string;
  id: string;
  image: string;
  isActive: boolean;
  nameRu: string;
  nameTm: string;
  order: number;
}
export interface images {
  Category?: Category;
  image?: string;
  Status?: {
    nameRu: string;
    id: string|number;
  };
  video?: string;
  productStatus?: string;
  title: string;
  discountPrice?: number;
  category?: string;
  feedBackNumb: number;
  articule: string;
  desc: string;
  additionalInfoRu: string;
  additionalInfoTm: string;
  barcode: string;
  brandId: string;
  categoryId: string;
  compositionRu: string;
  compositionTm: string;
  currentSellPrice: string;
  descriptionRu: string;
  descriptionTm: string;
  discountType: string;
  discountValue: string;
  hashtags: [];
  id: string;
  imageFive: string;
  imageFour: string;
  imageOne: string;
  imageThree: string;
  imageTwo: string;
  incomePrice: string;
  isActive: boolean;
  isDisabled: boolean;
  limit: string;
  nameRu: string;
  nameTm: string;
  order: number;
  productStatusId: number;
  segmentId: string;
  sellPrice: string | number;
  stock: string | number;
  subCategoryId: string;
  unit: string;
  updatedAt: string;
  usageRu: string;
  usageTm: string;
  waitListCount: string;
}
export interface Product {
  product: images;
  products?: images[];
  color?: string;
  bgcolor?: string;
  width?: string | number;
  height?: string | number;
  br?: number | string;
  isLoading?: boolean;
}
export interface testData {
  Category?: Category;
  image?: string;
  video?: string;
  productStatus?: string;
  title: string;
  discountPrice?: number;
  category?: string;
  feedBackNumb: number;
  articule: string;
  desc: string;
  additionalInfoRu: string;
  additionalInfoTm: string;
  barcode: string;
  brandId: string;
  categoryId: string;
  compositionRu: string;
  compositionTm: string;
  currentSellPrice: string;
  descriptionRu: string;
  descriptionTm: string;
  discountType: string;
  discountValue: string;
  hashtags: [];
  id: string;
  imageFive: string;
  imageFour: string;
  imageOne: string;
  imageThree: string;
  imageTwo: string;
  incomePrice: string;
  isActive: boolean;
  isDisabled: boolean;
  limit: string;
  nameRu: string;
  nameTm: string;
  order: number;
  productStatusId: number;
  segmentId: string;
  sellPrice: string | number;
  stock: string | number;
  subCategoryId: string;
  unit: string;
  updatedAt: string;
  usageRu: string;
  usageTm: string;
  waitListCount: string;
}
